version: '3.8'

services:
  postgres:
    container_name: wetunesdb
    image: postgres:15
    volumes:
      - wetunesdata:/var/lib/postgresql/data
    ports:
      - '5500:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wetunes
      POSTGRES_PASSWORD: password

volumes:
  wetunesdata:
