import type { Metadata } from 'next';
import { Work_Sans as FontSans } from 'next/font/google';
import '@/styles/globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} dark font-sans antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
